project:
  type: website

website:
  title: "km2023"
  open-graph: true
  favicon: favicon-16x16.png
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/andreslagerlof/km2023
    logo: fff_logo_50pct.png
    background: light
  page-footer: 
    left: "FFF KM"
    right: "Sportcheferna FFF"
    border: true
    background: light
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

